# Generated by Django 3.2.18 on 2023-05-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_review_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
