# Generated by Django 3.2.18 on 2023-06-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('결제전', '결제전'), ('배송준비중', '배송준비중'), ('배송중', '배송중'), ('배송완료', '배송완료'), ('취소됨', '취소됨'), ('반송중', '반송중')], default='결제전', max_length=15),
        ),
    ]
