# Generated by Django 3.2.18 on 2023-06-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20230612_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
