# Generated by Django 3.2.18 on 2023-06-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[(0, '결제전'), (1, '배송준비중'), (2, '배송중'), (3, '배송완료'), (4, '취소됨'), (5, '반송중')], default=0, max_length=15),
        ),
    ]
