# Generated by Django 3.2.18 on 2023-06-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_order_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
