# Generated by Django 3.2.18 on 2023-05-30 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secondhands', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_purchase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_purchases', to=settings.AUTH_USER_MODEL),
        ),
    ]
