# Generated by Django 3.2.18 on 2023-06-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_product',
            name='road_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
