# Generated by Django 3.2.18 on 2023-06-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondhands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='s_product',
            name='status',
            field=models.CharField(choices=[('1', ''), ('2', '예약중'), ('3', '거래완료')], default='', max_length=10),
        ),
    ]
