# Generated by Django 3.2.18 on 2023-06-13 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointlog',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='pointlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pointlog',
            name='type',
        ),
        migrations.CreateModel(
            name='PointLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=False)),
                ('type_detail', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('point_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_log_itmes', to='accounts.pointlog')),
            ],
        ),
    ]
