# Generated by Django 3.2.18 on 2023-05-24 00:59

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=stores.models.Store.store_image_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=stores.models.ProductImage.product_image_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.product')),
            ],
        ),
    ]
