# Generated by Django 3.2.18 on 2023-06-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20230531_1557'),
        ('stores', '0002_auto_20230607_1343'),
    ]

    operations = [
    ]
