# Generated by Django 3.2.18 on 2023-06-08 01:17

from django.db import migrations
import imagekit.models.fields
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_merge_0002_auto_20230531_1557_0002_auto_20230607_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='detail_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=stores.models.ProductImage.product_image_path),
        ),
    ]
