# Generated by Django 3.2.18 on 2023-06-08 02:16

from django.db import migrations
import imagekit.models.fields
import stores.models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_productimage_detail_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='detail_image',
        ),
        migrations.AddField(
            model_name='product',
            name='detail_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=stores.models.Product.p_product_image_path),
        ),
    ]
